# Generated by Django 2.2.5 on 2019-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.TextField()),
                ('senderEmail', models.EmailField(max_length=254)),
                ('details', models.TextField()),
            ],
        ),
    ]
